// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKMgs2NTjvmc44XY1fuJFAVL7yjIi6GJQ',
    appId: '1:422077123956:web:630ab701a7f556214ab021',
    messagingSenderId: '422077123956',
    projectId: 'joga10-ec65f',
    authDomain: 'joga10-ec65f.firebaseapp.com',
    storageBucket: 'joga10-ec65f.firebasestorage.app',
    measurementId: 'G-GSC78RKCJM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4DCR1Wqk077B8bYzP_49zcHvyt1CTrQM',
    appId: '1:422077123956:android:692bc376d51d61b04ab021',
    messagingSenderId: '422077123956',
    projectId: 'joga10-ec65f',
    storageBucket: 'joga10-ec65f.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWMXm6wYCVWAigvpIY31Cjyynsv9dY6GA',
    appId: '1:422077123956:ios:24e6c5e9233a72024ab021',
    messagingSenderId: '422077123956',
    projectId: 'joga10-ec65f',
    storageBucket: 'joga10-ec65f.firebasestorage.app',
    iosBundleId: 'br.com.joga10.app',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWMXm6wYCVWAigvpIY31Cjyynsv9dY6GA',
    appId: '1:422077123956:ios:24e6c5e9233a72024ab021',
    messagingSenderId: '422077123956',
    projectId: 'joga10-ec65f',
    storageBucket: 'joga10-ec65f.firebasestorage.app',
    iosBundleId: 'br.com.joga10.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKMgs2NTjvmc44XY1fuJFAVL7yjIi6GJQ',
    appId: '1:422077123956:web:0dd4cff941d78acc4ab021',
    messagingSenderId: '422077123956',
    projectId: 'joga10-ec65f',
    authDomain: 'joga10-ec65f.firebaseapp.com',
    storageBucket: 'joga10-ec65f.firebasestorage.app',
    measurementId: 'G-HZZ6H3XJH9',
  );
}
